export const courseKeywords = {
  loathed: -1,
  "fucking hate": -1,
  "fucked over": -1,
  "fuck over": -1,
  worst: -1,
  horribly: -1,
  horrible: -1,
  terrible: -1,
  hate: -1,
  "Do not take": -1,
  "Don't take": -1,
  abomination: -1,
  ridiculously: -1,
  ridiculous: -1,
  incompetence: -1,
  "fuck up": -1,
  "dumpster fire": -1,
  "least favorite": -1,
  "least fav": -1,
  disorganized: -1,
  mess: -1,
  typo: -1,
  hard: -1,
  harder: -1,
  failed: -1,
  hardest: -1,
  ass: -1,
  wtf: -1,
  "single good thing": -1,
  poor: -1,
  brutal: -1,
  "fed up": -1,
  "time-consuming": -1,
  "bad rep": -1,
  difficult: -1,
  challenging: -1,
  "never liked": -1,
  annoying: -1,
  "no reason": -1,
  "without reason": -1,
  "no warning": -1,
  "without warning": -1,
  bad: -1,
  retaking: -1,
  shit: -1,
  retake: -1,
  unfair: -1,
  crap: -1,
  dumb: -1,
  dumbest: -1,
  complacent: -1,
  sick: -1,
  "screw over": -1,

  // // work format
  // prelim: 0,
  // final: 0,
  // exam: 0,
  // test: 0,
  // project: 0,
  // pset: 0,

  // // problem, answer
  // problem: 0,
  // answer: 0,

  // workload: 0,

  // // grade
  // grade: 0,
  // curve: 0,
  // mean: 0,
  // median: 0,
  // "standard deviation": 0,
  // sd: 0,
  // curved: 0,
  // uncurved: 0,

  // // tools
  // canvas: 0,
  // gradescope: 0,

  // // class
  // lecture: 0,
  // class: 0,
  // "office hour": 0,

  // // people
  // prof: 0,
  // profs: 0,
  // professor: 0,
  // professors: 0,
  // ta: 0,
  // tas: 0,
  // consultant: 0,
  // consultants: 0,

  // // time
  // hour: 0,
  // hr: 0,
  // min: 0,
  // deadline: 0,

  fine: 1,
  "can't go wrong": 1,
  agree: 1,
  agreeable: 1,
  liked: 1,
  useful: 1,
  helpful: 1,
  doable: 1,
  "wasn't too bad": 1,
  "not harsh": 1,
  manageable: 1,
  straightforward: 1,
  "plenty of resources": 1,
  easier: 1,
  enjoy: 1,
  enjoyed: 1,
  enjoyable: 1,
  satisfied: 1,
  satisfying: 1,
  easy: 1,
  chill: 1,
  fun: 1,
  interesting: 1,
  "easy A": 1,
  best: 1,
}
