export const courseKeywords = {
  loathed: -3,
  "fucking hate": -3,
  "fucked over": -3,
  "fuck over": -3,
  worst: -3,
  horribly: -3,
  horrible: -3,
  terrible: -3,
  hate: -3,
  "Do not take": -3,
  "Don't take": -3,
  abomination: -3,
  ridiculously: -3,
  ridiculous: -3,
  "least favorite": -2,
  "least fav": -2,
  disorganized: -2,
  mess: -2,
  typo: -2,
  hard: -2,
  harder: -2,
  failed: -2,
  hardest: -2,
  rolled: -2,
  ass: -2,
  wtf: -2,
  "single good thing": -2,
  poor: -2,
  brutal: -2,
  "fed up": -2,
  "time-consuming": -2,
  "bad rep": -2,
  difficult: -2,
  challenging: -2,
  "never liked": -2,
  annoying: -1,
  "no reason": -1,
  "without reason": -1,
  "no warning": -1,
  "without warning": -1,
  bad: -1,
  retaking: -1,
  retake: -1,
  unfair: -1,
  complacent: -1,
  // sick: -1,

  // // work format
  // prelim: 0,
  // final: 0,
  // exam: 0,
  // test: 0,
  // project: 0,
  // pset: 0,

  // // problem, answer
  // problem: 0,
  // answer: 0,

  // workload: 0,

  // // grade
  // grade: 0,
  // curve: 0,
  // mean: 0,
  // median: 0,
  // "standard deviation": 0,
  // sd: 0,
  // curved: 0,
  // uncurved: 0,

  // // tools
  // canvas: 0,
  // gradescope: 0,

  // // class
  // lecture: 0,
  // class: 0,
  // "office hour": 0,

  // // people
  // prof: 0,
  // profs: 0,
  // professor: 0,
  // professors: 0,
  // ta: 0,
  // tas: 0,
  // consultant: 0,
  // consultants: 0,

  // // time
  // hour: 0,
  // hr: 0,
  // min: 0,
  // deadline: 0,

  fine: 1,
  useful: 1,
  helpful: 1,
  doable: 1,
  "wasn't too bad": 1,
  "not harsh": 1,
  manageable: 1,
  straightforward: 2,
  "plenty of resources": 2,
  easier: 2,
  enjoy: 2,
  enjoyed: 2,
  enjoyable: 2,
  satisfied: 2,
  satisfying: 2,
  easy: 2,
  chill: 2,
  fun: 2,
  interesting: 2,
  "easy A": 3,
}
